title: Centro educativo Nuestra señora de la Salceda
description: Página creada con Jekyll y GitHub Pages
# remote_theme: mmistakes/minimal-mistakes@4.33.0
remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - index.md
  - ciclos.md
  - about.md
  - contact.md
